select * from customer;

--1.Total revenue generated by Male vs Female customers.
select gender,sum(purchase_amount) as revenue 
from customer
group by gender;

--2.Which customers used a discount but still spend more than average purchased amount.
select customer_id,purchase_amount from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer);

--3.Which are the top 5 products with highest average review rating.
select item_purchased,round(avg(review_rating::numeric),2) from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4.Compare average purchase amount between standard and express shipping.
select shipping_type,avg(purchase_amount) from customer
group by shipping_type
having shipping_type in ('Standard','Express');

--5.Do subscribed user spend more.Compare average spend and total revenue between suscribed and non suscribed user
select subscription_status, count(customer_id) as total_customer, round(avg(purchase_amount),2) as average_spend, sum(purchase_amount) as total_spend from customer
group by subscription_status
order by average_spend;

--6.Which 5 products have highest percentage of purchase with discount applied.
select item_purchased,round(100*avg(case when discount_applied='Yes' then 1 else 0 end),2) as discount_rate from customer
group by item_purchased
order by discount_rate desc
limit 5;

--7.Segment customer into new, returning and loyal based on previous purchase and show the count of each segment
with customer_type as (
select previous_purchases,
case 
	when previous_purchases<=1 then 'New'
	when previous_purchases between 1 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment,count(*) as "No. of customers"
from customer_type
group by customer_segment;

--8.what are top 3 product purchased within each category.
with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders from item_counts
where item_rank<=3;

--9.Are customer who are repeat buyers(more than 5 orders) more likely to subscribe.
select subscription_status, count(customer_id)
from customer
where previous_purchases>=5
group by subscription_status;

--10.Revenue contribution of each age group.
select age_grouped,sum(purchase_amount)
from customer
group by age_grouped
order by sum(purchase_amount) desc;